### ISSUE TITLE
Officialize plugin

### ISSUE THREAD

**Issue by pepicrft** [MontakOleg/asdf-xcbeautify#6]
Thanks a lot for maintaining this one @MontakOleg. Would you consider making this plugin official by moving it to the [mise-plugins](https://github.com/mise-plugins/) organization or adding it to the [registry](https://github.com/mise-plugins/registry)? By doing so, developers won't have to add the plugin first. They'll simply do `mise install xcbeautify` and that's it. You can read more about `mise-plugins` [here](https://github.com/mise-plugins/.github/blob/main/profile/README.md)

**Comment by MontakOleg** [comment]
Hi, sounds good, I initiated transfer to @jdx

**Comment by jdx** [comment]
apologies, the transfer expired, could you send it again?

**Comment by MontakOleg** [comment]
@jdx sure! Done.

**Comment by MontakOleg** [comment]
It looks like mise-plugins registry already has `asdf-xcbeautify` plugin from MacPaw – https://github.com/mise-plugins/registry/blob/main/plugins/xcbeautify

<img width="699" alt="image" src="https://github.com/mise-plugins/asdf-xcbeautify/assets/1800899/44a2bffd-04d7-4ff1-99d1-e9217d142e8c">

As I understand if we change it to `mise-plugins/asdf-xcbeautify` users will not see "community plugin" warning.

@nekrich would you mind this change?
